//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddReminderDetail
    {
        public int Id { get; set; }
        public string MobileNumber { get; set; }
        public string WhatsAppNumber { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public Nullable<bool> IsSms { get; set; }
        public Nullable<bool> IsWhatsApp { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<int> AddedById { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
