//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApiSource()
        {
            this.BankStatements = new HashSet<BankStatement>();
            this.BankAccounts = new HashSet<BankAccount>();
        }
    
        public int Id { get; set; }
        public string ApiName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<byte> ApiTypeId { get; set; }
        public string ApiUserId { get; set; }
        public string ApiPassword { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<int> ApiPackid { get; set; }
        public string CallbackId { get; set; }
        public Nullable<decimal> ApiBal { get; set; }
        public Nullable<decimal> ActualBal { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StatusCheckTime { get; set; }
        public Nullable<bool> IsAutoStatusCheck { get; set; }
        public Nullable<int> RequestGap { get; set; }
        public Nullable<decimal> BlockAmount { get; set; }
        public Nullable<int> WaitTime { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string FullAddress { get; set; }
        public Nullable<int> ResendWaitTime { get; set; }
        public string BaseUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankStatement> BankStatements { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
    }
}
