//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmiForReminder
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EmiDate { get; set; }
        public Nullable<decimal> EmiAmount { get; set; }
        public Nullable<int> SetReminderId { get; set; }
        public Nullable<int> EmiStatus { get; set; }
        public Nullable<decimal> ReceivedPayment { get; set; }
        public string PaymentDetail { get; set; }
        public string UploadImage { get; set; }
        public Nullable<System.DateTime> ReceivedEmiDate { get; set; }
    
        public virtual PaymentStatu PaymentStatu { get; set; }
        public virtual SetReminder SetReminder { get; set; }
    }
}
