//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EZSMdbEntitie : DbContext
    {
        public EZSMdbEntitie()
            : base("name=EZSMdbEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<AddMember> AddMembers { get; set; }
        public virtual DbSet<AddReminderDetail> AddReminderDetails { get; set; }
        public virtual DbSet<AmtType> AmtTypes { get; set; }
        public virtual DbSet<ApiSource> ApiSources { get; set; }
        public virtual DbSet<BankStatement> BankStatements { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<EmailAPI> EmailAPIs { get; set; }
        public virtual DbSet<EmiForReminder> EmiForReminders { get; set; }
        public virtual DbSet<ExcelData> ExcelDatas { get; set; }
        public virtual DbSet<FilterRule> FilterRules { get; set; }
        public virtual DbSet<KYCDistrictList> KYCDistrictLists { get; set; }
        public virtual DbSet<KYCDocument> KYCDocuments { get; set; }
        public virtual DbSet<KYCStateList> KYCStateLists { get; set; }
        public virtual DbSet<MapMenuToRole> MapMenuToRoles { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<OrgType> OrgTypes { get; set; }
        public virtual DbSet<OtherPaymentReminder> OtherPaymentReminders { get; set; }
        public virtual DbSet<ParentUserDataList> ParentUserDataLists { get; set; }
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ReminderPaymentType> ReminderPaymentTypes { get; set; }
        public virtual DbSet<ReminderSetting> ReminderSettings { get; set; }
        public virtual DbSet<ReminderSettingMember> ReminderSettingMembers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RuleList> RuleLists { get; set; }
        public virtual DbSet<server> servers { get; set; }
        public virtual DbSet<ServerPaymentReminder> ServerPaymentReminders { get; set; }
        public virtual DbSet<SetReminder> SetReminders { get; set; }
        public virtual DbSet<SoftwareType> SoftwareTypes { get; set; }
        public virtual DbSet<StateList> StateLists { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TransferType> TransferTypes { get; set; }
        public virtual DbSet<TxnType> TxnTypes { get; set; }
        public virtual DbSet<VendorUserList> VendorUserLists { get; set; }
        public virtual DbSet<WhatsAppApi> WhatsAppApis { get; set; }
        public virtual DbSet<SentReminderData> SentReminderDatas { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<PhotoGallery> PhotoGalleries { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<GramPanchayat> GramPanchayats { get; set; }
        public virtual DbSet<JoinU> JoinUs { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
    }
}
