//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterRule
    {
        public int Id { get; set; }
        public string FixLength { get; set; }
        public Nullable<int> RuleId { get; set; }
        public Nullable<bool> IsAllowSpace { get; set; }
        public Nullable<bool> IsAllowDuplicated { get; set; }
        public string StartWith { get; set; }
        public string EndWith { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual RuleList RuleList { get; set; }
        public virtual User User { get; set; }
    }
}
