//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinU
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string GuardianName { get; set; }
        public string MobileNumber { get; set; }
        public string AlternateMobileNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Village { get; set; }
        public Nullable<int> GramPanchayatId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string PinCode { get; set; }
        public string Education { get; set; }
        public string FullAddress { get; set; }
        public string AadharNumber { get; set; }
        public string PanNumber { get; set; }
        public string UniqueId { get; set; }
        public Nullable<System.DateTime> JoiningTime { get; set; }
    }
}
