//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYCDocument
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AurthSignName { get; set; }
        public string AurthSignNameImg { get; set; }
        public string PanCardNum { get; set; }
        public string PanCardImg { get; set; }
        public string AadharCardNum { get; set; }
        public string AadharImage { get; set; }
        public string PolicyImg { get; set; }
        public string CancelCheckImg { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> Pin { get; set; }
        public string PhoneNum { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<bool> IsKYC { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string SelfImage { get; set; }
    
        public virtual KYCDistrictList KYCDistrictList { get; set; }
        public virtual KYCStateList KYCStateList { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
