//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherPaymentReminder
    {
        public int Id { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<decimal> RemainingPayment { get; set; }
        public Nullable<decimal> ReceivedPayment { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string PaymentDetail { get; set; }
        public string UploadImage { get; set; }
        public Nullable<int> ReminderStatus { get; set; }
        public Nullable<int> SetReminderId { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
    
        public virtual PaymentStatu PaymentStatu { get; set; }
        public virtual SetReminder SetReminder { get; set; }
    }
}
