//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string DomainName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool api { get; set; }
        public bool Retail { get; set; }
        public bool monytransfear { get; set; }
        public bool Getway { get; set; }
        public bool Bilpayment { get; set; }
        public bool Aeps { get; set; }
        public bool Basic { get; set; }
        public bool Roffer { get; set; }
        public bool Singlevendor { get; set; }
        public bool Multivendor { get; set; }
        public string Softwaretype { get; set; }
    }
}
