//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentReminderData
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string MobileNumber { get; set; }
        public string WhatsAppNumber { get; set; }
        public string Email { get; set; }
        public string SendMessage { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
        public Nullable<int> SendBy { get; set; }
    }
}
