//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class server
    {
        public int Id { get; set; }
        public string Servername { get; set; }
        public string IP { get; set; }
        public string Discription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ServerType { get; set; }
    }
}
