//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetReminder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetReminder()
        {
            this.EmiForReminders = new HashSet<EmiForReminder>();
            this.OtherPaymentReminders = new HashSet<OtherPaymentReminder>();
            this.ServerPaymentReminders = new HashSet<ServerPaymentReminder>();
        }
    
        public int id { get; set; }
        public int MemberId { get; set; }
        public int ReminderPaymentTypeId { get; set; }
        public string Software_Server_other_name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Project_startDate { get; set; }
        public Nullable<decimal> TotalPayment_Payment { get; set; }
        public Nullable<decimal> ReceivedPayment { get; set; }
        public Nullable<decimal> RemainingPayment { get; set; }
        public Nullable<bool> IsGst { get; set; }
        public string GstPercent { get; set; }
        public string TotalEmi { get; set; }
        public Nullable<decimal> EmiAmount { get; set; }
        public string ReceivedAccountNumber { get; set; }
        public Nullable<System.DateTime> FirstEmiDate { get; set; }
        public string Emidays { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public string ServerPaymenttype { get; set; }
        public Nullable<bool> Isdelete { get; set; }
        public Nullable<int> AddedbyId { get; set; }
        public Nullable<int> UpdatedbyId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<System.DateTime> otherReminderDate1 { get; set; }
        public Nullable<System.DateTime> otherReminderDate2 { get; set; }
        public Nullable<System.DateTime> otherReminderDate3 { get; set; }
        public Nullable<System.DateTime> Software_Server_StartDate { get; set; }
        public Nullable<bool> IsStop { get; set; }
    
        public virtual AddMember AddMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmiForReminder> EmiForReminders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherPaymentReminder> OtherPaymentReminders { get; set; }
        public virtual ReminderPaymentType ReminderPaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerPaymentReminder> ServerPaymentReminders { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
