//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Attchement { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string Deparment { get; set; }
        public string Massage { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string projectName { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual StatusType StatusType { get; set; }
        public virtual User User { get; set; }
    }
}
