//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorUserList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorUserList()
        {
            this.ParentUserDataLists = new HashSet<ParentUserDataList>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<byte> RoleId { get; set; }
        public Nullable<decimal> ChildUserBal { get; set; }
        public Nullable<decimal> Due_Amt { get; set; }
        public Nullable<decimal> AddAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<long> lapuId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentUserDataList> ParentUserDataLists { get; set; }
    }
}
